[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = false
enforceSerializableSessionState = false

[logger]
level = "warning"

[theme]
base = "light"

# Configuraciones específicas para Streamlit 1.46.0
[ui]
hideTopBar = false
